name: VineriumZiplines
version: 1.0
author: SaintQd
main: org.saintqd.vineriumziplines.VineriumZiplines
api-version: 1.21.11
depend: [VineriumLib]
permissions:
  vineriumziplines.admin:
    description: Access to admin commands.
    default: op